//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigortamWcf
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferModel", Namespace="http://schemas.datacontract.org/2004/07/Sigortam.Service.Model")]
    public partial class OfferModel : object
    {
        
        private string ConpanyLogoField;
        
        private string ConpanyNameField;
        
        private string DescField;
        
        private string PlateField;
        
        private long PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConpanyLogo
        {
            get
            {
                return this.ConpanyLogoField;
            }
            set
            {
                this.ConpanyLogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConpanyName
        {
            get
            {
                return this.ConpanyNameField;
            }
            set
            {
                this.ConpanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plate
        {
            get
            {
                return this.PlateField;
            }
            set
            {
                this.PlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SigortamWcf.ISigortamWcf")]
    public interface ISigortamWcf
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISigortamWcf/TeklifHesaplama", ReplyAction="http://tempuri.org/ISigortamWcf/TeklifHesaplamaResponse")]
        System.Threading.Tasks.Task<SigortamWcf.OfferModel[]> TeklifHesaplamaAsync(string plate, string Tckn, string stRuhsatSeriKodu, string stRuhsatSeriNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISigortamWcfChannel : SigortamWcf.ISigortamWcf, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SigortamWcfClient : System.ServiceModel.ClientBase<SigortamWcf.ISigortamWcf>, SigortamWcf.ISigortamWcf
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SigortamWcfClient() : 
                base(SigortamWcfClient.GetDefaultBinding(), SigortamWcfClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISigortamWcf.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SigortamWcfClient(EndpointConfiguration endpointConfiguration) : 
                base(SigortamWcfClient.GetBindingForEndpoint(endpointConfiguration), SigortamWcfClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SigortamWcfClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SigortamWcfClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SigortamWcfClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SigortamWcfClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SigortamWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SigortamWcf.OfferModel[]> TeklifHesaplamaAsync(string plate, string Tckn, string stRuhsatSeriKodu, string stRuhsatSeriNo)
        {
            return base.Channel.TeklifHesaplamaAsync(plate, Tckn, stRuhsatSeriKodu, stRuhsatSeriNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISigortamWcf))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISigortamWcf))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55062/SigortamWcf.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SigortamWcfClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISigortamWcf);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SigortamWcfClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISigortamWcf);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISigortamWcf,
        }
    }
}
